# Data Structures, Functions, Numpy & Pandas

# Section A: Data Structures & Control Structures

1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [1]:
nums = [10, 20, 30, 40, 50]

In [2]:
nums

In [3]:
# Append
nums.append(60)

In [4]:
"After append(60):", nums

In [5]:
# extend
nums.extend([70, 80])

In [6]:
"After extend([70, 80]):", nums

In [7]:
# insert
nums.insert(2, 25)

In [8]:
"After insert(2, 25):", nums

In [9]:
# remove
nums.remove(40)  # removes first occurrence of 40

In [10]:
"After remove(40):", nums

In [11]:
# pop
popped = nums.pop()  # removes last element

In [12]:
"After pop():", nums, "| Popped value:", popped

In [13]:
# index
"Index of 25:", nums.index(25)

In [14]:
# count
"Count of 20:", nums.count(20)

In [15]:
nums.sort()

In [16]:
"After sort():", nums

In [17]:
nums.reverse()

In [18]:
"After reverse():", nums

In [19]:
nums.clear()
"After clear():", nums

-------------------------------------------------------------------------------------------------------

2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [20]:
students = ("Alice", "Bob", "Charlie")

In [27]:
"Original tuple:", students

('Original tuple:', ('Alice', 'Bob', 'Charlie'))

In [35]:
try:
    students[1] = "David"
except TypeError as e:
    print("Error:", e)

Error: 'tuple' object does not support item assignment


3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [30]:
my_set = {1, 2, 2, 3, 4, 4, 5}

In [31]:
my_set

{1, 2, 3, 4, 5}

-------------------------------------------------------------------------------------------------------

4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [36]:
person = {"name": "Raj", "age": 25, "city": "Pune"}

In [37]:
person["age"] = 26

In [38]:
person

{'name': 'Raj', 'age': 26, 'city': 'Pune'}

In [39]:
person["email"] = "raj@example.com"

In [40]:
person

{'name': 'Raj', 'age': 26, 'city': 'Pune', 'email': 'raj@example.com'}

-------------------------------------------------------------------------------------------------------

5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message. 

In [47]:
age = int(input("Age is: "))
if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Age is: 56
Eligible to vote


-------------------------------------------------------------------------------------------------------

6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [ ]:
marks = float(input("Enter marks: "))
if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")

-------------------------------------------------------------------------------------------------------

7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [ ]:
num = int(input("Enter a number: "))
if num > 0:
    if num % 2 == 0:
        print("Positive Even")
    else:
        print("Positive Odd")
elif num == 0:
    print("Zero")
else:
    print("Negative")

-------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------

# Section B: Numpy

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [55]:
import numpy as np

In [58]:
scalar = np.array(5)
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[10, 20, 30], [40, 50, 60]])

In [59]:
scalar

array(5)

In [60]:
arr1

array([1, 2, 3, 4, 5])

In [61]:
arr2

array([[10, 20, 30],
       [40, 50, 60]])

-------------------------------------------------------------------------------------------------------

9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [62]:
import numpy as np

In [63]:
data = np.random.randint(0, 100, (4, 4))

In [64]:
data

array([[79, 59,  2, 91],
       [58,  6, 76,  8],
       [ 3, 84, 36, 93],
       [64, 36,  2, 99]])

-------------------------------------------------------------------------------------------------------

10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [70]:
import pandas as pd

In [71]:
mat = np.arange(1, 10).reshape(3, 3)

In [72]:
df = pd.DataFrame(mat, columns=['A', 'B', 'C'])

In [73]:
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

-------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------

# Section C: Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [74]:
import pandas as pd

In [75]:
data = {
    "Name": ["Asha", "Ravi", "Neha", "Asha", "Vikram", "Rita", "Mohan", "Amit", "Ravi", "Sita"],
    "Age": [25, 30, 28, 25, 35, 27, 31, 29, 30, 26],
    "City": ["Pune", "Delhi", "Mumbai", "Pune", "Delhi", "Chennai", "Kolkata", "Pune", "Delhi", "Mumbai"],
    "Salary": [50000, 60000, 58000, 50000, None, 62000, 59000, 61000, 60000, None]
}

In [76]:
df = pd.DataFrame(data)

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 448.0+ bytes


In [78]:
df.describe()

Age        Salary
count  10.000000      8.000000
mean   28.600000  57500.000000
std     3.098387   4780.914437
min    25.000000  50000.000000
25%    26.250000  56000.000000
50%    28.500000  59500.000000
75%    30.000000  60250.000000
max    35.000000  62000.000000

In [79]:
df[["Name", "City"]]

Name     City
0    Asha     Pune
1    Ravi    Delhi
2    Neha   Mumbai
3    Asha     Pune
4  Vikram    Delhi
5    Rita  Chennai
6   Mohan  Kolkata
7    Amit     Pune
8    Ravi    Delhi
9    Sita   Mumbai

In [80]:
df = df.drop("City", axis=1)

In [81]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

In [82]:
df = df.drop_duplicates()

In [83]:
df

Name  Age   Salary
0    Asha   25  50000.0
1    Ravi   30  60000.0
2    Neha   28  58000.0
4  Vikram   35  57500.0
5    Rita   27  62000.0
6   Mohan   31  59000.0
7    Amit   29  61000.0
9    Sita   26  57500.0